from flask import Flask, render_template, request, redirect, url_for, session
from werkzeug.security import generate_password_hash, check_password_hash
import os
import re
import psycopg
from psycopg.rows import dict_row
from psycopg import errors
from datetime import date, datetime
app = Flask(__name__)
app.secret_key = "mastihub-secret-key"

DATABASE_URL = os.environ.get("DATABASE_URL")

ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin123"
DAILY_LIMIT = 1000
POINTS_PER_100 = 10

MISSIONS = [
    ("Daily Quiz", 100),
    ("Tap Challenge", 100),
    ("Memory Challenge", 100),
    ("Puzzle Mission", 100),
    ("Quick Challenge", 100),
    ("Speed Challenge", 100),
    ("Bonus Mission", 100),
    ("Lucky Mission", 100),
    ("Final Challenge", 100),
    ("Daily Bonus", 100)
]


def get_db():
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL is not set")

    return psycopg.connect(
        DATABASE_URL,
        row_factory=dict_row
    )


def init_db():
    conn = get_db()

    conn.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL,
            points INTEGER DEFAULT 0,
            today_points INTEGER DEFAULT 0,
            last_date TEXT
        )
    """)

    conn.execute("""
        CREATE TABLE IF NOT EXISTS completed_missions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            mission_id INTEGER NOT NULL,
            completed_date TEXT NOT NULL,
            UNIQUE(user_id, mission_id, completed_date)
        )
    """)

    conn.execute("""
        CREATE TABLE IF NOT EXISTS withdrawals (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            amount INTEGER NOT NULL,
            points_used INTEGER NOT NULL,
            upi TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'Pending',
            created_at TEXT NOT NULL,
            utr TEXT,
            paid_at TEXT
        )
    """)

    conn.execute("""
        ALTER TABLE withdrawals
        ADD COLUMN IF NOT EXISTS utr TEXT
    """)

    conn.execute("""
        ALTER TABLE withdrawals
        ADD COLUMN IF NOT EXISTS paid_at TEXT
    """)

    conn.execute("""
        CREATE TABLE IF NOT EXISTS platform_revenue (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            amount REAL NOT NULL,
            source TEXT NOT NULL,
            created_at TEXT NOT NULL
        )
    """)

    # Digital Store products
    conn.execute("""
        CREATE TABLE IF NOT EXISTS store_products (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            description TEXT NOT NULL,
            price INTEGER NOT NULL,
            file_path TEXT NOT NULL,
            active BOOLEAN NOT NULL DEFAULT TRUE
        )
    """)

    # Add starter products only once
    products = [
        ("AI Video Prompts", "10 AI video ideas aur cinematic prompts", 29, "ai_video_prompts.txt"),
        ("Website Templates", "Website banane ke liye starter guide", 49, "website_templates.txt"),
        ("Instagram Creator Pack", "Hooks, captions aur hashtags", 29, "instagram_creator_pack.txt"),
    ]
    for name, description, price, filename in products:
        conn.execute(
            """
            INSERT INTO store_products (name, description, price, file_path)
            SELECT %s, %s, %s, %s
            WHERE NOT EXISTS (
                SELECT 1 FROM store_products WHERE file_path = %s
            )
            """,
            (name, description, price, filename, filename)
        )

    # Manual UPI orders; download access is granted only after admin verification
    conn.execute("""
        CREATE TABLE IF NOT EXISTS store_orders (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            product_id INTEGER NOT NULL,
            amount INTEGER NOT NULL,
            status TEXT NOT NULL DEFAULT 'Pending',
            utr TEXT,
            created_at TEXT NOT NULL,
            verified_at TEXT
        )
    """)

    conn.commit()
    conn.close()



@app.route("/store")
def store():
    if "user_id" not in session:
        return redirect(url_for("login"))

    conn = get_db()
    try:
        products = conn.execute("""
            SELECT id, name, description, price
            FROM store_products
            WHERE active = TRUE
            ORDER BY id
        """).fetchall()
    finally:
        conn.close()

    return render_template("store.html", products=products)



@app.route("/store/order/<int:product_id>", methods=["POST"])
def store_order(product_id):
    if "user_id" not in session:
        return redirect(url_for("login"))

    conn = get_db()
    try:
        product = conn.execute(
            "SELECT id, price FROM store_products WHERE id = %s AND active = TRUE",
            (product_id,)
        ).fetchone()

        if not product:
            return redirect(url_for("store"))

        order = conn.execute(
            """
            INSERT INTO store_orders
                (user_id, product_id, amount, status, created_at)
            VALUES (%s, %s, %s, 'Pending', %s)
            RETURNING id
            """,
            (session["user_id"], product["id"], product["price"],
             datetime.now().isoformat(timespec="seconds"))
        ).fetchone()
        conn.commit()
        return redirect(url_for("store_payment", order_id=order["id"]))
    finally:
        conn.close()


@app.route("/store/pay/<int:order_id>")
def store_payment(order_id):
    if "user_id" not in session:
        return redirect(url_for("login"))

    conn = get_db()
    try:
        order = conn.execute(
            """
            SELECT o.*, p.name AS product_name
            FROM store_orders o
            JOIN store_products p ON p.id = o.product_id
            WHERE o.id = %s AND o.user_id = %s
            """,
            (order_id, session["user_id"])
        ).fetchone()
    finally:
        conn.close()

    if not order:
        return redirect(url_for("store"))

    return render_template(
        "store_payment.html",
        order=order,
        store_upi_id=os.environ.get("STORE_UPI_ID", "8896340758@axl"),
        message=request.args.get("msg", "")
    )


@app.route("/store/order/<int:order_id>/utr", methods=["POST"])
def store_submit_utr(order_id):
    if "user_id" not in session:
        return redirect(url_for("login"))

    utr = request.form.get("utr", "").strip()
    if not re.fullmatch(r"[A-Za-z0-9]{6,30}", utr):
        return redirect(url_for(
            "store_payment", order_id=order_id, msg="UTR number sahi bharo."
        ))

    conn = get_db()
    try:
        order = conn.execute(
            """
            SELECT id FROM store_orders
            WHERE id = %s AND user_id = %s AND status = 'Pending'
            """,
            (order_id, session["user_id"])
        ).fetchone()

        if not order:
            return redirect(url_for("store"))

        conn.execute(
            "UPDATE store_orders SET utr = %s WHERE id = %s AND user_id = %s",
            (utr, order_id, session["user_id"])
        )
        conn.commit()
    finally:
        conn.close()

    return redirect(url_for(
        "store_payment", order_id=order_id, msg="UTR submit ho gaya. Admin verification pending hai."
    ))


@app.route("/store/download/<int:order_id>")
def store_download(order_id):
    if "user_id" not in session:
        return redirect(url_for("login"))

    conn = get_db()
    try:
        order = conn.execute(
            """
            SELECT p.file_path
            FROM store_orders o
            JOIN store_products p ON p.id = o.product_id
            WHERE o.id = %s AND o.user_id = %s AND o.status = 'Paid'
            """,
            (order_id, session["user_id"])
        ).fetchone()
    finally:
        conn.close()

    allowed_files = {
        "ai_video_prompts.txt",
        "website_templates.txt",
        "instagram_creator_pack.txt"
    }
    if not order or order["file_path"] not in allowed_files:
        return "Download sirf verified, approved order ke liye available hai.", 403

    from flask import send_from_directory
    return send_from_directory(
        "store_files", order["file_path"], as_attachment=True
    )

@app.route("/about")
def about():
    return render_template("about.html")


@app.route("/contact")
def contact():
    return render_template("contact.html")


@app.route("/privacy")
def privacy():
    return render_template("privacy.html")


@app.route("/")
def home():

    if "user_id" not in session:
        return redirect(url_for("login"))

    conn = get_db()

    user = conn.execute(
        "SELECT * FROM users WHERE id = %s",
        (session["user_id"],)
    ).fetchone()

    if not user:
        conn.close()
        session.clear()
        return redirect(url_for("login"))

    today = str(date.today())

    completed_rows = conn.execute(
        """
        SELECT mission_id
        FROM completed_missions
        WHERE user_id = %s
        AND completed_date = %s
        """,
        (user["id"], today)
    ).fetchall()

    conn.close()

    completed = {row["mission_id"] for row in completed_rows}

    missions = []

    for i, (title, points) in enumerate(MISSIONS, start=1):
        missions.append({
            "id": i,
            "title": title,
            "points": points,
            "completed": i in completed
        })

    return render_template(
        "index.html",
        user=user,
        missions=missions
    )


@app.route("/register", methods=["GET", "POST"])
def register():

    if request.method == "POST":

        username = request.form.get("username", "").strip()
        password = request.form.get("password", "")

        if len(username) < 3:
            return "Username कम से कम 3 अक्षर का होना चाहिए।"

        if len(password) < 6:
            return "Password कम से कम 6 अक्षर का होना चाहिए।"

        conn = get_db()

        try:
            conn.execute(
                """
                INSERT INTO users (username, password, points, today_points, last_date)
                VALUES (%s, %s, 0, 0, %s)
                """,
                (username, generate_password_hash(password), str(date.today()))
            )

            conn.commit()

        except errors.UniqueViolation:
            conn.close()
            return "यह username पहले से मौजूद है।"

        conn.close()

        return redirect(url_for("login"))

    return render_template("register.html")


@app.route("/login", methods=["GET", "POST"])
def login():

    if request.method == "POST":

        username = request.form.get("username", "").strip()
        password = request.form.get("password", "")

        if username == ADMIN_USERNAME and password == ADMIN_PASSWORD:
            session.clear()
            session["admin"] = True
            return redirect(url_for("admin"))

        conn = get_db()

        user = conn.execute(
            "SELECT * FROM users WHERE username = %s",
            (username,)
        ).fetchone()

        conn.close()

        if user and check_password_hash(user["password"], password):

            session["user_id"] = user["id"]

            return redirect(url_for("home"))

        return "Username या password गलत है।"

    return render_template("login.html")


@app.route("/logout")
def logout():

    session.clear()

    return redirect(url_for("login"))


@app.route("/mission/<int:mission_id>", methods=["GET", "POST"])
def mission(mission_id):
    if "user_id" not in session:
        return redirect(url_for("login"))

    if mission_id < 1 or mission_id > len(MISSIONS):
        return redirect(url_for("home"))

    conn = get_db()

    try:
        # Lock the user's row while processing a reward.
        user = conn.execute(
            "SELECT * FROM users WHERE id = %s FOR UPDATE",
            (session["user_id"],)
        ).fetchone()

        if not user:
            conn.rollback()
            session.clear()
            return redirect(url_for("login"))

        today = str(date.today())

        if user["last_date"] != today:
            conn.execute(
                """
                UPDATE users
                SET today_points = 0, last_date = %s
                WHERE id = %s
                """,
                (today, user["id"])
            )
            user = conn.execute(
                "SELECT * FROM users WHERE id = %s",
                (user["id"],)
            ).fetchone()

        already_done = conn.execute(
            """
            SELECT id FROM completed_missions
            WHERE user_id = %s AND mission_id = %s
            AND completed_date = %s
            """,
            (user["id"], mission_id, today)
        ).fetchone()

        if already_done:
            conn.commit()
            return redirect(url_for("home"))

        if user["today_points"] >= DAILY_LIMIT:
            conn.commit()
            return redirect(url_for("home"))

        if request.method == "POST":
            if request.form.get("completed") != "1":
                conn.rollback()
                return "Invalid game completion.", 400

            reward = min(
                MISSIONS[mission_id - 1][1],
                DAILY_LIMIT - user["today_points"]
            )

            # The database uniqueness rule prevents duplicate daily rewards.
            inserted = conn.execute(
                """
                INSERT INTO completed_missions
                    (user_id, mission_id, completed_date)
                VALUES (%s, %s, %s)
                ON CONFLICT (user_id, mission_id, completed_date)
                DO NOTHING
                RETURNING id
                """,
                (user["id"], mission_id, today)
            ).fetchone()

            if not inserted:
                conn.commit()
                return "Mission already completed.", 409

            conn.execute(
                """
                UPDATE users
                SET points = points + %s,
                    today_points = today_points + %s,
                    last_date = %s
                WHERE id = %s
                """,
                (reward, reward, today, user["id"])
            )
            conn.commit()
            return "OK", 200

        conn.commit()
        return render_template(
            "game.html",
            title=MISSIONS[mission_id - 1][0],
            points=MISSIONS[mission_id - 1][1],
            mission_id=mission_id
        )

    except Exception:
        conn.rollback()
        app.logger.exception("Mission processing failed")
        return "Game process nahi ho saka. Dobara try karo.", 500

    finally:
        conn.close()


@app.route("/withdraw", methods=["GET", "POST"])
def withdraw():

    if "user_id" not in session:
        return redirect(url_for("login"))

    conn = get_db()

    user = conn.execute(
        "SELECT * FROM users WHERE id = %s",
        (session["user_id"],)
    ).fetchone()

    if request.method == "POST":

        try:
            amount = int(request.form.get("amount", "0"))
        except ValueError:
            amount = 0

        upi = request.form.get("upi", "").strip()

        # 100 points = ₹10
        points_needed = amount * 10

        if amount < 10:
            conn.close()
            return render_template(
                "withdraw.html",
                user=user,
                error="Minimum withdrawal ₹10 है।"
            )

        if not upi:
            conn.close()
            return render_template(
                "withdraw.html",
                user=user,
                error="UPI ID डालें।"
            )

        if points_needed > user["points"]:
            conn.close()
            return render_template(
                "withdraw.html",
                user=user,
                error="आपके पास पर्याप्त points नहीं हैं।"
            )

        conn.execute(
            """
            INSERT INTO withdrawals
            (user_id, amount, points_used, upi, status, created_at)
            VALUES (%s, %s, %s, %s, 'Pending', %s)
            """,
            (
                user["id"],
                amount,
                points_needed,
                upi,
                str(date.today())
            )
        )

        conn.execute(
            """
            UPDATE users
            SET points = points - %s
            WHERE id = %s
            """,
            (points_needed, user["id"])
        )

        conn.commit()
        conn.close()

        return redirect(url_for("history"))

    conn.close()

    return render_template(
        "withdraw.html",
        user=user
    )


@app.route("/history")
def history():

    if "user_id" not in session:
        return redirect(url_for("login"))

    conn = get_db()

    withdrawals = conn.execute(
        """
        SELECT *
        FROM withdrawals
        WHERE user_id = %s
        ORDER BY id DESC
        """,
        (session["user_id"],)
    ).fetchall()

    conn.close()

    return render_template(
        "history.html",
        withdrawals=withdrawals
    )




@app.route("/admin/revenue", methods=["POST"])
def admin_revenue():
    if not session.get("admin"):
        return redirect(url_for("login"))

    try:
        amount = float(request.form.get("amount", "0"))
    except ValueError:
        amount = 0

    source = request.form.get("source", "").strip()

    if amount <= 0 or not source:
        return redirect(url_for("admin"))

    conn = get_db()
    conn.execute("""
        INSERT INTO platform_revenue
        (amount, source, created_at)
        VALUES (%s, %s, %s)
    """, (amount, source, str(date.today())))

    conn.commit()
    conn.close()

    return redirect(url_for("admin"))



@app.route("/admin/revenue/<int:revenue_id>/delete", methods=["GET", "POST"])
def delete_revenue(revenue_id):

    if not session.get("admin"):
        return redirect(url_for("login"))

    conn = get_db()

    conn.execute(
        "DELETE FROM platform_revenue WHERE id = %s",
        (revenue_id,)
    )

    conn.commit()
    conn.close()

    return redirect(url_for("admin"))

@app.route("/admin")
def admin():

    if not session.get("admin"):
        return redirect(url_for("login"))

    conn = get_db()

    store_orders = conn.execute("""
        SELECT o.id, o.amount, o.status, o.utr, o.created_at,
               u.username, p.name AS product_name
        FROM store_orders o
        JOIN users u ON u.id = o.user_id
        JOIN store_products p ON p.id = o.product_id
        ORDER BY o.id DESC
    """).fetchall()

    withdrawals = conn.execute("""
        SELECT withdrawals.*, users.username
        FROM withdrawals
        JOIN users ON users.id = withdrawals.user_id
        ORDER BY withdrawals.id DESC
    """).fetchall()

    users = conn.execute("""
        SELECT id, username, points
        FROM users
        ORDER BY id DESC
    """).fetchall()

    total_users = conn.execute(
        "SELECT COUNT(*) AS c FROM users"
    ).fetchone()["c"]

    total_points = conn.execute(
        "SELECT COALESCE(SUM(points), 0) AS s FROM users"
    ).fetchone()["s"]

    total_withdrawals = conn.execute(
        "SELECT COUNT(*) AS c FROM withdrawals"
    ).fetchone()["c"]

    approved_withdrawals = conn.execute("""
        SELECT COALESCE(SUM(amount), 0) AS s
        FROM withdrawals
        WHERE status = 'Paid'
    """).fetchone()["s"]

    pending_withdrawals = conn.execute("""
        SELECT COALESCE(SUM(amount), 0) AS s
        FROM withdrawals
        WHERE status = 'Pending'
    """).fetchone()["s"]

    # 1000 points = ₹100
    reward_value = total_points / 10

    total_revenue = conn.execute(
        "SELECT COALESCE(SUM(amount), 0) AS s FROM platform_revenue"
    ).fetchone()["s"]

    revenue_history = conn.execute("""
        SELECT id, amount, source, created_at
        FROM platform_revenue
        ORDER BY id DESC
    """).fetchall()

    admin_net = total_revenue - approved_withdrawals
    available_payout = max(0, admin_net)

    conn.close()

    return render_template(
        "admin.html",
        store_orders=store_orders,
        withdrawals=withdrawals,
        users=users,
        total_users=total_users,
        total_points=total_points,
        reward_value=reward_value,
        total_withdrawals=total_withdrawals,
        approved_withdrawals=approved_withdrawals,
        pending_withdrawals=pending_withdrawals,
        total_revenue=total_revenue,
        revenue_history=revenue_history,
        admin_net=admin_net,
        available_payout=available_payout
    )


@app.route("/admin/withdraw/<int:withdrawal_id>/<action>", methods=["GET", "POST"])
def admin_withdraw(withdrawal_id, action):

    if not session.get("admin"):
        return redirect(url_for("login"))

    if action not in ("approve", "reject"):
        return redirect(url_for("admin"))

    conn = get_db()

    withdrawal = conn.execute(
        "SELECT * FROM withdrawals WHERE id = %s",
        (withdrawal_id,)
    ).fetchone()

    if not withdrawal or withdrawal["status"] != "Pending":
        conn.close()
        return redirect(url_for("admin"))

    if action == "approve":

        # Platform revenue minus already paid withdrawals
        total_revenue = conn.execute(
            "SELECT COALESCE(SUM(amount), 0) AS s FROM platform_revenue"
        ).fetchone()["s"]

        paid_withdrawals = conn.execute(
            "SELECT COALESCE(SUM(amount), 0) AS s FROM withdrawals WHERE status='Paid'"
        ).fetchone()["s"]

        available_payout = float(total_revenue or 0) - float(paid_withdrawals or 0)

        if float(withdrawal["amount"]) > available_payout:
            conn.close()
            return render_template(
                "payment.html",
                withdrawal=withdrawal,
                error=f"Platform balance ₹{max(0, available_payout):.2f} है। इस withdrawal के लिए पर्याप्त balance नहीं है।"
            )

        if request.method == "GET":
            conn.close()
            return render_template(
                "payment.html",
                withdrawal=withdrawal
            )

        utr = request.form.get("utr", "").strip()

        if not utr:
            conn.close()
            return render_template(
                "payment.html",
                withdrawal=withdrawal,
                error="UTR / Transaction ID डालें।"
            )

        conn.execute(
            """
            UPDATE withdrawals
            SET status='Paid',
                utr=%s,
                paid_at=%s
            WHERE id=%s
            """,
            (utr, str(date.today()), withdrawal_id)
        )

    else:

        conn.execute(
            "UPDATE users SET points=points+%s WHERE id=%s",
            (withdrawal["points_used"], withdrawal["user_id"])
        )

        conn.execute(
            "UPDATE withdrawals SET status='Rejected' WHERE id=%s",
            (withdrawal_id,)
        )

    conn.commit()
    conn.close()

    return redirect(url_for("admin"))


@app.route("/admin/logout")
def admin_logout():
    session.clear()
    return redirect(url_for("login"))


# init_db() disabled for game testing



@app.route("/game/tap")
def tap_game():
    if "user_id" not in session:
        return redirect(url_for("login"))
    return render_template("tap_game.html")


if __name__ == "__main__":
    app.run(
        host="0.0.0.0",
        port=5000,
        debug=True
    )

